# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 883f76ab3105eef18f57e005ff5802cb588621e8fa1df38ed3fb32fb044e66b10e7831e850044044616fec1655e6b222db98b621a435a198deb1424331ec6afa

test:
  secret_key_base: 6f019f8fb7f90ed8f2b07642a878c3db79ae186c73c4c3ee96e27f5f0e6bd0bdf627ec0905846adb045140549a790c5c40a08f3111d98e054a369d0f875c2e7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
